# Generated by Django 5.1.7 on 2025-12-25 03:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE_PLAN", "创建调整方案"),
                            ("ADD_MOVE", "添加调整明细"),
                            ("VALIDATE_PLAN", "验证调整方案"),
                            ("SUBMIT_PLAN", "提交调整方案"),
                            ("APPROVE_PLAN", "批准调整方案"),
                            ("APPLY_PLAN", "生效调整方案"),
                            ("UPDATE_CADRE", "更新干部信息"),
                            ("CREATE_CADRE", "创建干部"),
                            ("DELETE_CADRE", "删除干部"),
                            ("UPDATE_ORG", "更新组织信息"),
                            ("CREATE_ORG", "创建组织"),
                            ("DELETE_ORG", "删除组织"),
                            ("IMPORT_DATA", "导入数据"),
                            ("EXPORT_DATA", "导出数据"),
                            ("LOGIN", "登录"),
                            ("LOGOUT", "登出"),
                            ("UPDATE_RISK_TAG", "更新风险标签"),
                            ("CREATE_CONFLICT", "创建矛盾关系"),
                            ("UPDATE_CONFLICT", "更新矛盾关系"),
                            ("DELETE_CONFLICT", "删除矛盾关系"),
                            ("OTHER", "其他操作"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=30,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="目标类型",
                    ),
                ),
                (
                    "target_id",
                    models.UUIDField(
                        blank=True, db_index=True, null=True, verbose_name="目标ID"
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="记录操作前后的数据变化、客户端信息等",
                        verbose_name="上下文信息",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="浏览器或客户端信息",
                        verbose_name="用户代理",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="操作时间"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "审计日志",
                "verbose_name_plural": "审计日志",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"],
                        name="audit_audit_action_0c6a84_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_audit_target__2d648a_idx",
                    ),
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="audit_audit_actor_i_1175ab_idx",
                    ),
                ],
            },
        ),
    ]
