# Generated by Django 5.1.7 on 2025-12-25 03:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadres", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConflictPair",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("WORK_CONFLICT", "工作矛盾"),
                            ("PERSONAL_CONFLICT", "个人矛盾"),
                            ("OTHER", "其他"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="矛盾类型",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("LOW", "低"), ("MEDIUM", "中"), ("HIGH", "高")],
                        db_index=True,
                        default="LOW",
                        max_length=10,
                        verbose_name="严重程度",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="启用"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "cadre_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts_as_a",
                        to="cadres.cadre",
                        verbose_name="干部A",
                    ),
                ),
                (
                    "cadre_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts_as_b",
                        to="cadres.cadre",
                        verbose_name="干部B",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_conflicts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "矛盾关系对",
                "verbose_name_plural": "矛盾关系对",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["cadre_a", "is_active"],
                        name="risk_rules__cadre_a_3d0e27_idx",
                    ),
                    models.Index(
                        fields=["cadre_b", "is_active"],
                        name="risk_rules__cadre_b_2d59dc_idx",
                    ),
                    models.Index(
                        fields=["severity", "is_active"],
                        name="risk_rules__severit_19aea2_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cadre_a", "cadre_b"), name="unique_cadre_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RiskPersonTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("B_KEY_PERSON", "B库重点人员"),
                            ("RELATIONSHIP_BAD", "关系复杂"),
                            ("SENSITIVE", "敏感人员"),
                            ("OTHER", "其他"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=20,
                        verbose_name="标签类型",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("LOW", "低"), ("MEDIUM", "中"), ("HIGH", "高")],
                        db_index=True,
                        default="LOW",
                        max_length=10,
                        verbose_name="风险等级",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="原因")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="启用"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "cadre",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_tag",
                        to="cadres.cadre",
                        verbose_name="干部",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_risk_tags",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "风险人员标签",
                "verbose_name_plural": "风险人员标签",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tag_type", "is_active"],
                        name="risk_rules__tag_typ_e0e244_idx",
                    ),
                    models.Index(
                        fields=["risk_level", "is_active"],
                        name="risk_rules__risk_le_b1aae7_idx",
                    ),
                ],
            },
        ),
    ]
