# Generated by Django 5.1.7 on 2025-12-25 03:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cadre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cadre_code",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="干部编号",
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=50, verbose_name="姓名"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女"), ("U", "未知")],
                        default="U",
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="出生日期"),
                ),
                (
                    "native_place",
                    models.CharField(blank=True, max_length=100, verbose_name="籍贯"),
                ),
                (
                    "ethnicity",
                    models.CharField(blank=True, max_length=20, verbose_name="民族"),
                ),
                (
                    "political_status",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="政治面貌"
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MIDDLE", "中专"),
                            ("COLLEGE", "大专"),
                            ("BACHELOR", "本科"),
                            ("MASTER", "硕士"),
                            ("DOCTOR", "博士"),
                            ("OTHER", "其他"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="学历层次",
                    ),
                ),
                (
                    "degree",
                    models.CharField(blank=True, max_length=50, verbose_name="学位"),
                ),
                (
                    "join_work_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="参加工作时间"
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(blank=True, null=True, verbose_name="入职时间"),
                ),
                (
                    "current_position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="现任职务"
                    ),
                ),
                (
                    "current_rank",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="现任职级"
                    ),
                ),
                (
                    "position_start_date",
                    models.DateField(blank=True, null=True, verbose_name="任现职时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "在职"),
                            ("TRANSFERRED", "调离"),
                            ("RETIRED", "退休"),
                            ("RESIGNED", "离职"),
                            ("SUSPENDED", "停职"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=dict, verbose_name="标签"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "干部",
                "verbose_name_plural": "干部",
                "ordering": ["status", "-position_start_date", "name"],
                "indexes": [
                    models.Index(
                        fields=["status", "education_level"],
                        name="cadres_cadr_status_5edfd1_idx",
                    ),
                    models.Index(
                        fields=["position_start_date"],
                        name="cadres_cadr_positio_d055da_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CadreResume",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position_title",
                    models.CharField(max_length=100, verbose_name="岗位职务"),
                ),
                ("start_date", models.DateField(verbose_name="开始时间")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "cadre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to="cadres.cadre",
                        verbose_name="干部",
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cadre_resumes",
                        to="orgs.orgunit",
                        verbose_name="工作单位",
                    ),
                ),
            ],
            options={
                "verbose_name": "干部履历",
                "verbose_name_plural": "干部履历",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["cadre", "-start_date"],
                        name="cadres_cadr_cadre_i_0f5ddb_idx",
                    )
                ],
            },
        ),
    ]
