# Generated by Django 5.1.7 on 2025-12-28 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadres", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonnelRoster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serial_number",
                    models.IntegerField(db_index=True, verbose_name="序号"),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=50, verbose_name="姓名"),
                ),
                (
                    "department",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="部门"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女"), ("U", "未知")],
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(blank=True, null=True, verbose_name="年龄"),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="出生年月"),
                ),
                (
                    "ethnicity",
                    models.CharField(blank=True, max_length=20, verbose_name="民族"),
                ),
                (
                    "native_place",
                    models.CharField(blank=True, max_length=100, verbose_name="籍贯"),
                ),
                (
                    "household_registration",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="户籍所在地"
                    ),
                ),
                (
                    "working_years",
                    models.IntegerField(blank=True, null=True, verbose_name="工龄"),
                ),
                (
                    "join_work_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="参加工作时间"
                    ),
                ),
                (
                    "join_prison_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="参加监狱工作时间"
                    ),
                ),
                (
                    "continuous_service_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="连续工龄计算时间"
                    ),
                ),
                (
                    "has_2years_grassroots",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="是否有2年基层工作经历"
                    ),
                ),
                (
                    "political_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("中共党员", "中共党员"),
                            ("共青团员", "共青团员"),
                            ("民主党派", "民主党派"),
                            ("群众", "群众"),
                            ("其他", "其他"),
                        ],
                        max_length=20,
                        verbose_name="政治面貌",
                    ),
                ),
                (
                    "join_party_date",
                    models.DateField(blank=True, null=True, verbose_name="入党时间"),
                ),
                (
                    "position",
                    models.CharField(blank=True, max_length=100, verbose_name="职务"),
                ),
                (
                    "promotion_category",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="晋升四高及以上序列分类"
                    ),
                ),
                (
                    "position_category",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="职务类别"
                    ),
                ),
                (
                    "current_position_years",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="任现职年限"
                    ),
                ),
                (
                    "current_position_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="任现职务时间"
                    ),
                ),
                (
                    "position_level",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="职务级别"
                    ),
                ),
                (
                    "position_rank",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="职务层次"
                    ),
                ),
                (
                    "same_level_leadership_years",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="任同级领导职务年限"
                    ),
                ),
                (
                    "same_level_leadership_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="任同级领导职务时间"
                    ),
                ),
                (
                    "same_level_rank_years",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="任同级领导职务层次时间年限",
                    ),
                ),
                (
                    "same_level_rank_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="任同级领导职务层次时间"
                    ),
                ),
                (
                    "current_rank_years",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="任现职级年限"
                    ),
                ),
                (
                    "current_rank_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="任现职级时间"
                    ),
                ),
                (
                    "calculation_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="量化计分起算时间"
                    ),
                ),
                (
                    "police_rank",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("一级警长", "一级警长"),
                            ("二级警长", "二级警长"),
                            ("三级警长", "三级警长"),
                            ("四级警长", "四级警长"),
                        ],
                        max_length=20,
                        verbose_name="现警员职级",
                    ),
                ),
                (
                    "police_rank_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="任现警员职级起算时间"
                    ),
                ),
                (
                    "first_set_rank",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="首套警员职级"
                    ),
                ),
                (
                    "first_set_rank_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="首套警员职级起算时间"
                    ),
                ),
                (
                    "first_promote_rank",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="首晋警员职级"
                    ),
                ),
                (
                    "first_promote_rank_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="首晋警员职级起算时间"
                    ),
                ),
                (
                    "work_charge",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="分管工作"
                    ),
                ),
                (
                    "fulltime_education",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="全日制教育学历"
                    ),
                ),
                (
                    "fulltime_school",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="全日制毕业院校"
                    ),
                ),
                (
                    "fulltime_major",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="全日制专业"
                    ),
                ),
                (
                    "fulltime_degree",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="全日制学位"
                    ),
                ),
                (
                    "fulltime_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="全日制入学时间"
                    ),
                ),
                (
                    "fulltime_graduate_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="全日制毕业时间"
                    ),
                ),
                (
                    "inservice_education",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="在职学历"
                    ),
                ),
                (
                    "inservice_school",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="在职毕业院校"
                    ),
                ),
                (
                    "inservice_form",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="学习形式"
                    ),
                ),
                (
                    "inservice_major",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="在职专业"
                    ),
                ),
                (
                    "inservice_degree",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="在职学位"
                    ),
                ),
                (
                    "inservice_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="在职入学时间"
                    ),
                ),
                (
                    "inservice_graduate_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="在职毕业时间"
                    ),
                ),
                (
                    "police_title",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("一级警督", "一级警督"),
                            ("二级警督", "二级警督"),
                            ("三级警督", "三级警督"),
                            ("一级警司", "一级警司"),
                            ("二级警司", "二级警司"),
                            ("三级警司", "三级警司"),
                            ("一级警员", "一级警员"),
                            ("二级警员", "二级警员"),
                            ("三级警员", "三级警员"),
                            ("四级警员", "四级警员"),
                        ],
                        max_length=20,
                        verbose_name="警衔",
                    ),
                ),
                (
                    "police_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="警号",
                    ),
                ),
                (
                    "profession_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="专业资格名称"
                    ),
                ),
                (
                    "profession_level",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="专业资格级别"
                    ),
                ),
                (
                    "technical_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="专业技术职务"
                    ),
                ),
                (
                    "counseling_cert_level",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="心理咨询证书级别"
                    ),
                ),
                (
                    "english_level",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="英语专业"
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "quarterly_remark",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="季度报表备注"
                    ),
                ),
                (
                    "dept_work_years",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="在本部门工作年限"
                    ),
                ),
                (
                    "dept_work_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="本部门工作时间"
                    ),
                ),
                (
                    "unit_work_years",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="在本单位年限"
                    ),
                ),
                (
                    "enter_unit_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="进入本单位时间"
                    ),
                ),
                (
                    "enter_unit_form",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="进入本单位形式"
                    ),
                ),
                (
                    "identity_source",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="身份来源"
                    ),
                ),
                (
                    "military_experience",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="军转干/部队经历"
                    ),
                ),
                (
                    "highest_education",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="最高学历"
                    ),
                ),
                (
                    "highest_school",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="最高学历毕业院校"
                    ),
                ),
                (
                    "education_level",
                    models.CharField(blank=True, max_length=50, verbose_name="学历"),
                ),
                (
                    "highest_major",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="最高学历专业"
                    ),
                ),
                (
                    "highest_degree",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="最高学位"
                    ),
                ),
                (
                    "major_category",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="最高学历专业类别"
                    ),
                ),
                (
                    "id_card",
                    models.CharField(
                        blank=True,
                        max_length=18,
                        null=True,
                        unique=True,
                        verbose_name="身份证号",
                    ),
                ),
                (
                    "id_card_inconsistent",
                    models.BooleanField(
                        default=False, verbose_name="出生年月与身份证信息不一致"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="电话"),
                ),
                (
                    "cert_level",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="证书级别"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_rosters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "花名册",
                "verbose_name_plural": "花名册",
                "ordering": ["serial_number", "department", "name"],
                "indexes": [
                    models.Index(
                        fields=["serial_number"], name="cadres_pers_serial__35ad34_idx"
                    ),
                    models.Index(
                        fields=["department"], name="cadres_pers_departm_79e3da_idx"
                    ),
                    models.Index(fields=["name"], name="cadres_pers_name_d4ec72_idx"),
                    models.Index(
                        fields=["police_number"], name="cadres_pers_police__f9bb90_idx"
                    ),
                    models.Index(
                        fields=["id_card"], name="cadres_pers_id_card_8ed2dc_idx"
                    ),
                ],
            },
        ),
    ]
