# Generated by Django 4.2.30 on 2026-09-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadres", "0002_personnelroster"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnelroster",
            name="annual_assessments",
            field=models.JSONField(blank=True, default=dict, verbose_name="年度考核"),
        ),
        migrations.AddField(
            model_name="personnelroster",
            name="clerk_date",
            field=models.DateField(blank=True, null=True, verbose_name="任干事时间"),
        ),
        migrations.AddField(
            model_name="personnelroster",
            name="is_clerk",
            field=models.CharField(blank=True, max_length=50, verbose_name="是否干事"),
        ),
        migrations.AlterField(
            model_name="personnelroster",
            name="current_position_date",
            field=models.DateField(blank=True, null=True, verbose_name="任现职时间"),
        ),
        migrations.AlterField(
            model_name="personnelroster",
            name="current_position_years",
            field=models.CharField(blank=True, max_length=20, verbose_name="任职年限"),
        ),
        migrations.AlterField(
            model_name="personnelroster",
            name="current_rank_date",
            field=models.DateField(blank=True, null=True, verbose_name="任级时间"),
        ),
        migrations.AlterField(
            model_name="personnelroster",
            name="current_rank_years",
            field=models.CharField(blank=True, max_length=20, verbose_name="任级年限"),
        ),
        migrations.AlterField(
            model_name="personnelroster",
            name="enter_unit_form",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="进入单位形式"
            ),
        ),
        migrations.AlterField(
            model_name="personnelroster",
            name="police_rank",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="现警员职级"
            ),
        ),
        migrations.AlterField(
            model_name="personnelroster",
            name="police_title",
            field=models.CharField(blank=True, max_length=50, verbose_name="警衔"),
        ),
        migrations.AlterField(
            model_name="personnelroster",
            name="political_status",
            field=models.CharField(blank=True, max_length=50, verbose_name="政治面貌"),
        ),
        migrations.AlterField(
            model_name="personnelroster",
            name="position_level",
            field=models.CharField(blank=True, max_length=50, verbose_name="级别"),
        ),
    ]
