# Generated by Django 5.1.7 on 2025-12-25 03:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadres", "0001_initial"),
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffingPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="方案标题")),
                ("description", models.TextField(blank=True, verbose_name="方案描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草案"),
                            ("SUBMITTED", "已提交"),
                            ("APPROVED", "已批准"),
                            ("APPLIED", "已生效"),
                            ("REJECTED", "已拒绝"),
                            ("CANCELED", "已取消"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="批准时间"
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="生效时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="批准人",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "人事调整方案",
                "verbose_name_plural": "人事调整方案",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffingPlanMove",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "move_type",
                    models.CharField(
                        choices=[
                            ("ASSIGN", "分配"),
                            ("REMOVE", "移除"),
                            ("TRANSFER", "调动"),
                        ],
                        default="TRANSFER",
                        max_length=20,
                        verbose_name="调整类型",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="调整原因"
                    ),
                ),
                (
                    "risk_snapshot",
                    models.JSONField(blank=True, default=dict, verbose_name="风险快照"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "cadre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_moves",
                        to="cadres.cadre",
                        verbose_name="干部",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_moves",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "from_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves_from",
                        to="orgs.orgunit",
                        verbose_name="原单位",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="staffing.staffingplan",
                        verbose_name="调整方案",
                    ),
                ),
                (
                    "to_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves_to",
                        to="orgs.orgunit",
                        verbose_name="目标单位",
                    ),
                ),
            ],
            options={
                "verbose_name": "调整明细",
                "verbose_name_plural": "调整明细",
                "ordering": ["plan", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrgMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role_in_unit",
                    models.CharField(
                        choices=[
                            ("SECRETARY", "书记"),
                            ("COMMITTEE_MEMBER", "委员"),
                            ("MEMBER", "成员"),
                            ("LEADER", "负责人"),
                            ("DEPUTY", "副职"),
                            ("OTHER", "其他"),
                        ],
                        default="MEMBER",
                        max_length=20,
                        verbose_name="单位内角色",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="是否主归属"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="生效日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "在职"), ("INACTIVE", "离职")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "cadre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="cadres.cadre",
                        verbose_name="干部",
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="orgs.orgunit",
                        verbose_name="组织单位",
                    ),
                ),
            ],
            options={
                "verbose_name": "组织归属",
                "verbose_name_plural": "组织归属",
                "ordering": ["-status", "-start_date"],
                "indexes": [
                    models.Index(
                        fields=["org_unit", "status"],
                        name="staffing_or_org_uni_3d3d74_idx",
                    ),
                    models.Index(
                        fields=["cadre", "status"],
                        name="staffing_or_cadre_i_b73e8a_idx",
                    ),
                    models.Index(
                        fields=["org_unit", "is_primary", "status"],
                        name="staffing_or_org_uni_820ff0_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True), ("status", "ACTIVE")),
                        fields=("cadre",),
                        name="unique_primary_active_membership",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="staffingplan",
            index=models.Index(
                fields=["status", "-created_at"], name="staffing_st_status_63e50b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffingplanmove",
            index=models.Index(
                fields=["plan", "-created_at"], name="staffing_st_plan_id_35b029_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffingplanmove",
            index=models.Index(
                fields=["to_unit", "-created_at"], name="staffing_st_to_unit_26b94e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffingplanmove",
            index=models.Index(
                fields=["cadre", "plan"], name="staffing_st_cadre_i_6bf0d0_idx"
            ),
        ),
    ]
