# Generated by Django 4.2.30 on 2026-09-03 14:32

import anonymous_evaluations.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="活动名称")),
                ("description", models.TextField(blank=True, verbose_name="活动说明")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("PUBLISHED", "填写中"),
                            ("CLOSED", "已关闭"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "dimensions_json",
                    models.JSONField(
                        default=anonymous_evaluations.models.default_dimensions,
                        validators=[anonymous_evaluations.models.validate_dimensions],
                        verbose_name="评价维度",
                    ),
                ),
                (
                    "min_valid_responses",
                    models.PositiveSmallIntegerField(
                        default=8,
                        validators=[django.core.validators.MinValueValidator(2)],
                        verbose_name="最小有效样本数",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                ("deadline_at", models.DateTimeField(verbose_name="截止时间")),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="关闭时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_anonymous_evaluation_campaigns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "匿名测评活动",
                "verbose_name_plural": "匿名测评活动",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_name_snapshot",
                    models.CharField(max_length=100, verbose_name="评价对象姓名快照"),
                ),
                (
                    "org_name_snapshot",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="组织名称快照"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="anonymous_evaluations.evaluationcampaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anonymous_evaluation_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "匿名测评对象",
                "verbose_name_plural": "匿名测评对象",
            },
        ),
        migrations.CreateModel(
            name="EvaluationResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "anonymous_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="匿名令牌",
                    ),
                ),
                (
                    "scores_json",
                    models.JSONField(default=dict, verbose_name="评分数据"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="具体建议")),
                (
                    "submitted_on",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="提交日期"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="anonymous_evaluations.evaluationcampaign",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="anonymous_evaluations.evaluationtarget",
                    ),
                ),
            ],
            options={
                "verbose_name": "匿名测评答卷",
                "verbose_name_plural": "匿名测评答卷",
            },
        ),
        migrations.CreateModel(
            name="EvaluationEligibility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "submitted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已提交"
                    ),
                ),
                (
                    "submitted_on",
                    models.DateField(blank=True, null=True, verbose_name="提交日期"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibilities",
                        to="anonymous_evaluations.evaluationcampaign",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anonymous_evaluation_eligibilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibilities",
                        to="anonymous_evaluations.evaluationtarget",
                    ),
                ),
            ],
            options={
                "verbose_name": "匿名测评资格",
                "verbose_name_plural": "匿名测评资格",
            },
        ),
        migrations.AddConstraint(
            model_name="evaluationtarget",
            constraint=models.UniqueConstraint(
                fields=("campaign", "user"),
                name="unique_evaluation_target_per_campaign",
            ),
        ),
        migrations.AddIndex(
            model_name="evaluationresponse",
            index=models.Index(
                fields=["campaign", "target"], name="anonymous_e_campaig_b2bb56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evaluationeligibility",
            index=models.Index(
                fields=["campaign", "evaluator", "submitted"],
                name="anonymous_e_campaig_c1660b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationeligibility",
            constraint=models.UniqueConstraint(
                fields=("target", "evaluator"), name="unique_evaluation_eligibility"
            ),
        ),
        migrations.AddIndex(
            model_name="evaluationcampaign",
            index=models.Index(
                fields=["status", "deadline_at"], name="anonymous_e_status_76ff6b_idx"
            ),
        ),
    ]
