# Generated by Django 4.2.30 on 2026-09-18 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgs", "0002_membership"),
        ("cadres", "0003_roster_new_template_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="批次名称")),
                (
                    "year",
                    models.CharField(blank=True, max_length=20, verbose_name="年度"),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="考察开始日期"
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="考察结束日期"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="批次说明")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("PUBLISHED", "填写中"),
                            ("CLOSED", "已关闭"),
                        ],
                        db_index=True,
                        default="PUBLISHED",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "form_types",
                    models.JSONField(default=list, verbose_name="下发的表单类型"),
                ),
                ("deadline_at", models.DateTimeField(verbose_name="截止时间")),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="关闭时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_knowing_people_campaigns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "知事识人考察批次",
                "verbose_name_plural": "知事识人考察批次",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InspectionTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("ATTACHMENT_2", "附件2 近距离考察干部自评表"),
                            ("ATTACHMENT_3", "附件3 个人述事表"),
                            ("ATTACHMENT_4", "附件4 中层领导班子评价表"),
                            ("ATTACHMENT_5", "附件5 支部述事表"),
                            (
                                "ATTACHMENT_6_1",
                                "附件6-1 中层领导班子测评（书记评各支部）",
                            ),
                            (
                                "ATTACHMENT_6_2",
                                "附件6-2 中层领导班子测评（本支部民警职工）",
                            ),
                            ("ATTACHMENT_7_1", "附件7-1 中层领导干部测评（评正职）"),
                            ("ATTACHMENT_7_2", "附件7-2 中层领导干部测评（评副职）"),
                            (
                                "ATTACHMENT_7_3",
                                "附件7-3 中层领导干部测评（评团队负责人）",
                            ),
                            (
                                "ATTACHMENT_7_4",
                                "附件7-4 中层领导干部测评（本支部干部）",
                            ),
                            ("ATTACHMENT_1", "附件1 谈话研判测评表"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="表单类型",
                    ),
                ),
                (
                    "filler_role",
                    models.CharField(
                        choices=[
                            ("MIDDLE_LEADER", "中层领导（含团队负责人）"),
                            ("BRANCH_LEADERSHIP", "党支部班子"),
                            ("BRANCH_SECRETARY", "党支部书记"),
                            ("BRANCH_COMMITTEE", "党支部支委"),
                            ("BRANCH_STAFF", "本支部民警职工"),
                            ("POLITICAL_LEADER", "政工领导"),
                            ("INSPECTION_TALKER", "谈话研判人员"),
                            ("MANUAL", "管理员指定"),
                        ],
                        default="MANUAL",
                        max_length=30,
                        verbose_name="填报身份",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待填报"),
                            ("DRAFT", "草稿"),
                            ("SUBMITTED", "已提交"),
                            ("RETURNED", "退回修改"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "assignee_name_snapshot",
                    models.CharField(max_length=100, verbose_name="填报人姓名快照"),
                ),
                (
                    "org_unit_name_snapshot",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="所属部门快照"
                    ),
                ),
                (
                    "branch_name_snapshot",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="所属支部快照"
                    ),
                ),
                (
                    "payload_json",
                    models.JSONField(blank=True, default=dict, verbose_name="填报内容"),
                ),
                (
                    "context_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="预填上下文"
                    ),
                ),
                (
                    "return_reason",
                    models.TextField(blank=True, verbose_name="退回原因"),
                ),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="退回时间"
                    ),
                ),
                (
                    "remind_count",
                    models.PositiveIntegerField(default=0, verbose_name="催办次数"),
                ),
                (
                    "reminded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近催办时间"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提交时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowing_people_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="填报人",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowing_people_tasks",
                        to="orgs.orgunit",
                        verbose_name="所属支部",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="knowing_people.inspectioncampaign",
                    ),
                ),
                (
                    "returned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returned_knowing_people_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="退回人",
                    ),
                ),
                (
                    "roster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowing_people_tasks",
                        to="cadres.personnelroster",
                        verbose_name="花名册人员",
                    ),
                ),
            ],
            options={
                "verbose_name": "知事识人填报任务",
                "verbose_name_plural": "知事识人填报任务",
                "ordering": ["campaign", "form_type", "assignee_name_snapshot"],
                "indexes": [
                    models.Index(
                        fields=["campaign", "status"],
                        name="knowing_peo_campaig_2ce5d6_idx",
                    ),
                    models.Index(
                        fields=["assignee", "status"],
                        name="knowing_peo_assigne_8f4b0b_idx",
                    ),
                    models.Index(
                        fields=["form_type", "status"],
                        name="knowing_peo_form_ty_840dba_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="inspectiontask",
            constraint=models.UniqueConstraint(
                fields=("campaign", "form_type", "assignee"),
                name="unique_knowing_people_task_per_form",
            ),
        ),
        migrations.AddIndex(
            model_name="inspectioncampaign",
            index=models.Index(
                fields=["status", "deadline_at"], name="knowing_peo_status_d5cf4a_idx"
            ),
        ),
    ]
