# Generated by Django 4.2.30 on 2026-09-17 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="任务名称")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CHALLENGING", "急难险重任务"),
                            ("OUTSTANDING", "突出任务"),
                        ],
                        max_length=20,
                        verbose_name="任务类型",
                    ),
                ),
                ("completed_on", models.DateField(verbose_name="完成日期")),
                (
                    "role",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="承担角色"
                    ),
                ),
                ("details", models.TextField(verbose_name="具体任务及作用发挥")),
                ("outcome", models.TextField(blank=True, verbose_name="完成成效")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "知事识人纪实",
                "verbose_name_plural": "知事识人纪实",
                "ordering": ["-completed_on", "-created_at"],
            },
        ),
    ]
