# Generated by Django 4.2.30 on 2026-08-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="角色代码"),
        ),
    ]
