# Generated by Django 4.2.30 on 2026-08-26 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadershipAssessmentFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_date", models.DateField(db_index=True)),
                (
                    "file_name",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                ("total_records", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_leadership_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version_date", "-upload_time"],
            },
        ),
        migrations.CreateModel(
            name="LeadershipAssessmentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("leadership_count", models.IntegerField(blank=True, null=True)),
                ("vacancy_count", models.IntegerField(blank=True, null=True)),
                ("team_leader_count", models.IntegerField(blank=True, null=True)),
                (
                    "team_leader_vacancy_count",
                    models.IntegerField(blank=True, null=True),
                ),
                ("average_age", models.FloatField(blank=True, null=True)),
                ("max_age", models.IntegerField(blank=True, null=True)),
                ("min_age", models.IntegerField(blank=True, null=True)),
                ("postgraduate_count", models.IntegerField(blank=True, null=True)),
                ("undergraduate_count", models.IntegerField(blank=True, null=True)),
                ("college_below_count", models.IntegerField(blank=True, null=True)),
                ("over_5_years_count", models.IntegerField(blank=True, null=True)),
                ("three_to_5_years_count", models.IntegerField(blank=True, null=True)),
                ("under_3_years_count", models.IntegerField(blank=True, null=True)),
                ("long_term_office_count", models.IntegerField(blank=True, null=True)),
                ("balanced_count", models.IntegerField(blank=True, null=True)),
                ("long_term_prison_count", models.IntegerField(blank=True, null=True)),
                ("ability_assessment", models.TextField(blank=True)),
                ("performance_2023", models.TextField(blank=True)),
                ("performance_2024", models.TextField(blank=True)),
                ("shortcomings", models.TextField(blank=True)),
                ("secretary_score", models.FloatField(blank=True, null=True)),
                ("democratic_score", models.FloatField(blank=True, null=True)),
                (
                    "total_score",
                    models.FloatField(blank=True, db_index=True, null=True),
                ),
                ("approval_rate", models.FloatField(blank=True, null=True)),
                ("ranking", models.IntegerField(blank=True, db_index=True, null=True)),
                ("adjustment_suggestion", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="leadership_assessments.leadershipassessmentfile",
                    ),
                ),
            ],
            options={
                "ordering": ["file", "ranking", "name"],
                "indexes": [
                    models.Index(
                        fields=["file", "ranking"],
                        name="leadership__file_id_2edfd0_idx",
                    ),
                    models.Index(fields=["name"], name="leadership__name_3957e2_idx"),
                    models.Index(
                        fields=["total_score"], name="leadership__total_s_688c53_idx"
                    ),
                ],
                "unique_together": {("file", "name")},
            },
        ),
        migrations.AddIndex(
            model_name="leadershipassessmentfile",
            index=models.Index(
                fields=["version_date"], name="leadership__version_773721_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leadershipassessmentfile",
            index=models.Index(
                fields=["is_active"], name="leadership__is_acti_52b4ad_idx"
            ),
        ),
    ]
