# Generated by Django 5.2.5 on 2026-08-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leadership_assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadershipassessmentfile",
            name="source_file",
            field=models.FileField(
                blank=True, null=True, upload_to="leadership_assessments/source/"
            ),
        ),
        migrations.AlterField(
            model_name="leadershipassessmentfile",
            name="file_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="leadershipassessmentfile",
            name="version_date",
            field=models.DateField(unique=True),
        ),
    ]
