# Generated by Django 4.2.30 on 2026-08-26 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_date", models.DateField(db_index=True)),
                (
                    "file_name",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                ("total_records", models.IntegerField(default=0)),
                ("category_counts", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version_date", "-upload_time"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50)),
                ("department", models.CharField(db_index=True, max_length=100)),
                ("position", models.CharField(max_length=100)),
                (
                    "position_category",
                    models.CharField(
                        choices=[
                            ("LEADERSHIP", "监狱领导班子成员"),
                            ("CORPORATE", "企业副总、工会主席（四高）"),
                            ("SECTION_CHIEF", "科室正职（含企业）"),
                            ("SECTION_DEPUTY", "科室副职（含企业）"),
                            ("INSTITUTION_2", "事业单位、群团组织、工作团队（二级）"),
                            ("INSTITUTION_4", "事业单位、群团组织、工作团队（四级）"),
                            ("PRISON_WARDEN", "监区长"),
                            ("INSTRUCTOR", "教导员"),
                            ("DEPUTY_PRISON", "副区（狱政）"),
                            ("DEPUTY_PRODUCTION", "副区（生产）"),
                            ("DEPUTY_EDUCATION", "副区（教育）"),
                            ("PRISON_TEAM", "监区工作团队"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("health_status", models.CharField(blank=True, max_length=50)),
                ("education", models.CharField(blank=True, max_length=50)),
                ("professional_title", models.CharField(blank=True, max_length=100)),
                ("join_prison_date", models.DateField(blank=True, null=True)),
                ("service_years", models.IntegerField(blank=True, null=True)),
                ("office_work_years", models.IntegerField(blank=True, null=True)),
                ("prison_work_years", models.IntegerField(blank=True, null=True)),
                ("main_business", models.TextField(blank=True)),
                ("annual_assessment_3years", models.TextField(blank=True)),
                ("quarterly_assessment", models.TextField(blank=True)),
                ("rewards_3years", models.TextField(blank=True)),
                ("penalties_3years", models.TextField(blank=True)),
                ("personality", models.TextField(blank=True)),
                ("ability_assessment", models.TextField(blank=True)),
                ("performance_2023", models.TextField(blank=True)),
                ("performance_2024", models.TextField(blank=True)),
                ("main_performance", models.TextField(blank=True)),
                ("shortcomings", models.TextField(blank=True)),
                ("evaluation_assessment", models.TextField(blank=True)),
                ("talk_assessment", models.TextField(blank=True)),
                ("comprehensive_assessment", models.TextField(blank=True)),
                ("seven_looks_score", models.FloatField(blank=True, null=True)),
                ("work_recognition_score", models.FloatField(blank=True, null=True)),
                ("talk_score", models.FloatField(blank=True, null=True)),
                ("comprehensive_score", models.FloatField(blank=True, null=True)),
                ("ranking", models.IntegerField(blank=True, db_index=True, null=True)),
                ("adjustment_suggestion", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="assessments.assessmentfile",
                    ),
                ),
            ],
            options={
                "ordering": ["file", "position_category", "ranking", "name"],
                "indexes": [
                    models.Index(
                        fields=["file", "position_category"],
                        name="assessments_file_id_2f4570_idx",
                    ),
                    models.Index(
                        fields=["file", "ranking"],
                        name="assessments_file_id_0eb70e_idx",
                    ),
                    models.Index(fields=["name"], name="assessments_name_0c3d2e_idx"),
                    models.Index(
                        fields=["department"], name="assessments_departm_0d5f26_idx"
                    ),
                ],
                "unique_together": {("file", "name", "department")},
            },
        ),
        migrations.AddIndex(
            model_name="assessmentfile",
            index=models.Index(
                fields=["version_date"], name="assessments_version_3773dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentfile",
            index=models.Index(
                fields=["is_active"], name="assessments_is_acti_a50109_idx"
            ),
        ),
    ]
