# Generated by Django 5.2.5 on 2026-08-27 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_assessmentfile_source_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentChangeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("CADRE_RECORD", "中层领导干部分析研判"),
                            ("LEADERSHIP_RECORD", "中层领导班子分析研判"),
                        ],
                        max_length=32,
                    ),
                ),
                ("resource_id", models.UUIDField(db_index=True)),
                ("version_date", models.DateField(db_index=True)),
                ("record_name", models.CharField(max_length=100)),
                ("changed_fields", models.JSONField(default=list)),
                ("before_values", models.JSONField(default=dict)),
                ("after_values", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_change_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["resource_type", "resource_id", "-created_at"],
                        name="assessments_resourc_a0ec32_idx",
                    )
                ],
            },
        ),
    ]
