# Generated by Django 4.2.30 on 2026-09-18 09:45

import cadre_recommendations.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadres", "0003_roster_new_template_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="活动名称")),
                ("description", models.TextField(blank=True, verbose_name="活动说明")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("PUBLISHED", "填写中"),
                            ("CLOSED", "已关闭"),
                        ],
                        db_index=True,
                        default="PUBLISHED",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "slot_config",
                    models.JSONField(
                        default=cadre_recommendations.models.default_slot_config,
                        validators=[cadre_recommendations.models.validate_slot_config],
                        verbose_name="各类岗位推荐人数",
                    ),
                ),
                (
                    "allow_self_recommend",
                    models.BooleanField(default=False, verbose_name="允许推荐本人"),
                ),
                (
                    "receiver_type",
                    models.CharField(
                        choices=[
                            ("USER", "指定用户"),
                            ("ORG_UNIT", "指定单位"),
                            ("ORG_ROLE", "单位角色"),
                        ],
                        default="USER",
                        max_length=20,
                        verbose_name="接收人类型",
                    ),
                ),
                (
                    "receiver_expr_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="接收人条件"
                    ),
                ),
                ("deadline_at", models.DateTimeField(verbose_name="截止时间")),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="关闭时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_recommendation_campaigns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "优秀干部推荐活动",
                "verbose_name_plural": "优秀干部推荐活动",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待填报"),
                            ("DRAFT", "草稿"),
                            ("SUBMITTED", "已提交"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "recommender_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BRANCH_SECRETARY", "党支部书记"),
                            ("BRANCH_COMMITTEE", "党支部支委"),
                            ("BRANCH_STAFF", "党支部全体民警职工"),
                        ],
                        max_length=30,
                        verbose_name="人员类别",
                    ),
                ),
                (
                    "assignee_name_snapshot",
                    models.CharField(max_length=100, verbose_name="填报人姓名快照"),
                ),
                (
                    "org_unit_name_snapshot",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="所属部门快照"
                    ),
                ),
                (
                    "branch_name_snapshot",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="所属支部快照"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提交时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="填报人",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="cadre_recommendations.recommendationcampaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "优秀干部推荐任务",
                "verbose_name_plural": "优秀干部推荐任务",
                "ordering": ["campaign", "assignee_name_snapshot"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationNomination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "post_category",
                    models.CharField(
                        choices=[
                            ("section_chief", "正科级领导干部"),
                            ("deputy_section_chief", "副科级领导干部"),
                            ("team_lead", "工作团队负责人（正职）"),
                            ("deputy_team_lead", "工作团队负责人（副职）"),
                            ("police_officer", "警员职级警察"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="岗位类别",
                    ),
                ),
                (
                    "slot_index",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="空位序号",
                    ),
                ),
                (
                    "name_snapshot",
                    models.CharField(max_length=50, verbose_name="姓名快照"),
                ),
                (
                    "department_snapshot",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="部门快照"
                    ),
                ),
                (
                    "position_snapshot",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="职务职级快照"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "roster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendation_nominations",
                        to="cadres.personnelroster",
                        verbose_name="被推荐人",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominations",
                        to="cadre_recommendations.recommendationtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "优秀干部推荐人选",
                "verbose_name_plural": "优秀干部推荐人选",
                "ordering": ["task", "post_category", "slot_index"],
            },
        ),
        migrations.AddIndex(
            model_name="recommendationtask",
            index=models.Index(
                fields=["campaign", "status"], name="cadre_recom_campaig_118e76_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendationtask",
            constraint=models.UniqueConstraint(
                fields=("campaign", "assignee"),
                name="unique_recommendation_task_per_assignee",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendationnomination",
            constraint=models.UniqueConstraint(
                fields=("task", "post_category", "slot_index"),
                name="unique_recommendation_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendationnomination",
            constraint=models.UniqueConstraint(
                fields=("task", "roster"), name="unique_recommendation_person_per_task"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationcampaign",
            index=models.Index(
                fields=["status", "deadline_at"], name="cadre_recom_status_913b25_idx"
            ),
        ),
    ]
