# Generated by Django 5.1.7 on 2025-12-25 03:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrgUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="组织编码",
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("BRANCH", "支部"),
                            ("DEPARTMENT", "部门"),
                            ("TEAM", "团队"),
                            ("DIVISION", "处室"),
                            ("OFFICE", "办公室"),
                        ],
                        db_index=True,
                        default="BRANCH",
                        max_length=20,
                        verbose_name="单位类型",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="启用"
                    ),
                ),
                (
                    "metrics_snapshot",
                    models.JSONField(blank=True, null=True, verbose_name="指标快照"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="orgs.orgunit",
                        verbose_name="上级单位",
                    ),
                ),
            ],
            options={
                "verbose_name": "组织单元",
                "verbose_name_plural": "组织单元",
                "ordering": ["unit_type", "sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["unit_type", "is_active"],
                        name="orgs_orguni_unit_ty_773bcc_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("code__isnull", False)),
                        fields=("code",),
                        name="unique_org_unit_code",
                    )
                ],
            },
        ),
    ]
