# Generated by Django 6.0 on 2025-12-29 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=True, verbose_name='是否主部门')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='职务')),
                ('is_manager', models.BooleanField(default=False, verbose_name='是否部门负责人')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memberships', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='orgs.orgunit', verbose_name='所属部门')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '部门成员',
                'verbose_name_plural': '部门成员',
                'ordering': ['-is_primary', '-is_manager', 'user__username'],
                'indexes': [models.Index(fields=['user', 'unit'], name='orgs_member_user_id_8394d3_idx'), models.Index(fields=['unit', 'is_primary'], name='orgs_member_unit_id_9ce16e_idx'), models.Index(fields=['is_manager'], name='orgs_member_is_mana_29a665_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('user', 'unit'), name='unique_active_membership')],
            },
        ),
    ]
