# Generated by Django 4.2.30 on 2026-08-26 16:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orgs", "0002_membership"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cycle_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=50,
                        verbose_name="考核周期",
                    ),
                ),
                (
                    "stage_code",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="阶段编码"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="下发批次名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("PUBLISHED", "已发布"),
                            ("CLOSED", "已关闭"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "deadline_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="截止时间"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="关闭时间"
                    ),
                ),
                (
                    "stats_total",
                    models.IntegerField(default=0, verbose_name="应填总数"),
                ),
                (
                    "stats_submitted",
                    models.IntegerField(default=0, verbose_name="已提交总数"),
                ),
                (
                    "stats_overdue",
                    models.IntegerField(default=0, verbose_name="逾期总数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_dispatch_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "下发批次",
                "verbose_name_plural": "下发批次",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "template_version",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="模板版本快照"
                    ),
                ),
                (
                    "assignee_type",
                    models.CharField(
                        choices=[
                            ("USER", "指定用户"),
                            ("ORG_UNIT", "指定单位"),
                            ("ORG_ROLE", "单位角色"),
                        ],
                        default="USER",
                        max_length=20,
                        verbose_name="填报人类型",
                    ),
                ),
                (
                    "assignee_id",
                    models.UUIDField(db_index=True, verbose_name="填报人或单位 ID"),
                ),
                (
                    "assignee_role_snapshot",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="填报人角色快照"
                    ),
                ),
                (
                    "assignee_name_snapshot",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="填报人姓名快照"
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("USER", "个人"), ("ORG_UNIT", "单位")],
                        default="USER",
                        max_length=20,
                        verbose_name="评价对象类型",
                    ),
                ),
                (
                    "target_id",
                    models.UUIDField(blank=True, null=True, verbose_name="评价对象 ID"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待填报"),
                            ("DRAFT", "草稿"),
                            ("SUBMITTED", "已提交"),
                            ("RETURNED", "退回修改"),
                            ("OVERDUE", "逾期未交"),
                            ("CLOSED", "已关闭"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "deadline_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="截止时间"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提交时间"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="关闭时间"
                    ),
                ),
                (
                    "reassign_reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="改派原因"
                    ),
                ),
                (
                    "reassign_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="改派时间"
                    ),
                ),
                (
                    "context_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="上下文信息"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="forms.dispatchbatch",
                    ),
                ),
                (
                    "org_unit_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orgs.orgunit",
                        verbose_name="所属单位快照",
                    ),
                ),
                (
                    "reassign_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_tasks_reassigned_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="改派人",
                    ),
                ),
                (
                    "reassign_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reassigned_form_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="改派给",
                    ),
                ),
            ],
            options={
                "verbose_name": "填报任务",
                "verbose_name_plural": "填报任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnlyOfficeDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="forms/tasks/", verbose_name="任务文档"),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "document_key",
                    models.CharField(
                        db_index=True,
                        max_length=128,
                        unique=True,
                        verbose_name="OnlyOffice 文档键",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="版本"),
                ),
                (
                    "last_saved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后保存时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onlyoffice_document",
                        to="forms.formtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "OnlyOffice 文档",
                "verbose_name_plural": "OnlyOffice 文档",
            },
        ),
        migrations.CreateModel(
            name="FormTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="模板编码",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="模板名称")),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="版本号"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="说明")),
                (
                    "schema_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="表单结构定义"
                    ),
                ),
                (
                    "scoring_rule_json",
                    models.JSONField(blank=True, null=True, verbose_name="评分规则"),
                ),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="forms/templates/",
                        verbose_name="原始 Excel 文件",
                    ),
                ),
                (
                    "source_file_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="原始文件名"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_form_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "表单模板",
                "verbose_name_plural": "表单模板",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormTaskAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("DISPATCH", "下发任务"),
                            ("REASSIGN", "改派任务"),
                            ("SAVE_DRAFT", "保存草稿"),
                            ("SUBMIT", "提交任务"),
                            ("RETURN", "退回修改"),
                            ("CLOSE", "关闭任务"),
                            ("REOPEN", "重新打开"),
                            ("DELETE", "删除任务"),
                        ],
                        max_length=20,
                        verbose_name="操作",
                    ),
                ),
                (
                    "before_json",
                    models.JSONField(blank=True, default=dict, verbose_name="操作前"),
                ),
                (
                    "after_json",
                    models.JSONField(blank=True, default=dict, verbose_name="操作后"),
                ),
                ("reason", models.TextField(blank=True, verbose_name="原因")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 地址"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="用户代理")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="forms.formtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务审计日志",
                "verbose_name_plural": "任务审计日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="formtask",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="forms.formtemplate",
            ),
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="版本号",
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(default=False, verbose_name="是否最终提交"),
                ),
                (
                    "payload_json",
                    models.JSONField(blank=True, default=dict, verbose_name="表单数据"),
                ),
                (
                    "score_json",
                    models.JSONField(blank=True, null=True, verbose_name="评分数据"),
                ),
                (
                    "attachments_json",
                    models.JSONField(blank=True, default=list, verbose_name="附件信息"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提交时间"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 地址"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="用户代理")),
                (
                    "return_reason",
                    models.TextField(blank=True, verbose_name="退回原因"),
                ),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="退回时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "returned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returned_form_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="退回人",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交人",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="forms.formtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "提交版本",
                "verbose_name_plural": "提交版本",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="DispatchRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "receiver_type",
                    models.CharField(
                        choices=[
                            ("USER", "指定用户"),
                            ("ORG_UNIT", "指定单位"),
                            ("ORG_ROLE", "单位角色"),
                        ],
                        max_length=20,
                        verbose_name="接收人类型",
                    ),
                ),
                (
                    "receiver_expr_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="接收人条件"
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("USER", "个人"), ("ORG_UNIT", "单位")],
                        default="USER",
                        max_length=20,
                        verbose_name="评价对象类型",
                    ),
                ),
                (
                    "target_expr_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="评价对象条件"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="forms.dispatchbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_dispatch_rules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatch_rules",
                        to="forms.formtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "下发规则",
                "verbose_name_plural": "下发规则",
            },
        ),
        migrations.AddIndex(
            model_name="formtemplate",
            index=models.Index(
                fields=["code", "version"], name="forms_formt_code_9c8b33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formtemplate",
            index=models.Index(
                fields=["is_active"], name="forms_formt_is_acti_d929af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formtask",
            index=models.Index(
                fields=["batch", "status"], name="forms_formt_batch_i_6d6a08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formtask",
            index=models.Index(
                fields=["assignee_type", "assignee_id"],
                name="forms_formt_assigne_ea42aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="formtask",
            index=models.Index(
                fields=["status", "deadline_at"], name="forms_formt_status_50f145_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="formtask",
            constraint=models.UniqueConstraint(
                fields=(
                    "batch",
                    "template",
                    "assignee_type",
                    "assignee_id",
                    "target_type",
                    "target_id",
                ),
                name="unique_form_task",
            ),
        ),
        migrations.AddConstraint(
            model_name="formsubmission",
            constraint=models.UniqueConstraint(
                fields=("task", "version"), name="unique_form_submission_version"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchbatch",
            index=models.Index(
                fields=["cycle_id", "stage_code"], name="forms_dispa_cycle_i_c51420_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchbatch",
            index=models.Index(fields=["status"], name="forms_dispa_status_f8c430_idx"),
        ),
    ]
