# Generated by Django 4.2.30 on 2026-08-26 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0005_restore_onlyoffice_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onlyofficedocument",
            name="document_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=128,
                null=True,
                unique=True,
                verbose_name="OnlyOffice 文档键",
            ),
        ),
        migrations.AlterField(
            model_name="onlyofficedocument",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="forms/tasks/", verbose_name="任务文档"
            ),
        ),
        migrations.AlterField(
            model_name="onlyofficedocument",
            name="task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onlyoffice_document",
                to="forms.formtask",
            ),
        ),
    ]
