# Generated by Django 4.2.30 on 2026-08-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0006_alter_onlyofficedocument_document_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatchbatch",
            name="deadline_at",
            field=models.DateTimeField(verbose_name="截止时间"),
        ),
    ]
