# Generated by Django 4.2.30 on 2026-08-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0007_alter_dispatchbatch_deadline_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formtask",
            name="deadline_at",
            field=models.DateTimeField(db_index=True, verbose_name="截止时间"),
        ),
    ]
