# Generated by Django 4.2.30 on 2026-09-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0009_restore_onlyoffice_legacy_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formtaskaudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("DISPATCH", "下发任务"),
                    ("REASSIGN", "改派任务"),
                    ("SAVE_DRAFT", "保存草稿"),
                    ("SUBMIT", "提交任务"),
                    ("RETURN", "退回修改"),
                    ("CLOSE", "关闭任务"),
                    ("REOPEN", "重新打开"),
                    ("DELETE", "删除任务"),
                    ("EXTEND_DEADLINE", "延长截止时间"),
                ],
                max_length=20,
                verbose_name="操作",
            ),
        ),
    ]
